name: Docker

on:
  pull_request:
    branches:
      - 'develop'
    paths:
      - '/Dockerfile'
  push:
    branches:
      - 'develop'
    paths-ignore:
      - '/.github/**'
      - '!/.github/workflows/docker.yml'
      - '/.gitignore'
      - '/.vscode/**'
      - '/LICENSE'
      - '/README.md'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    needs: ['test']
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache amd64 Docker layers
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-buildx-linux/amd64-${{ github.sha }}
          path: /tmp/.buildx-cache/linux/amd64
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/ectoplasmhq/june
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - name: Build and publish
        uses: docker/build-push-action@v2
        with:
          cache-from: type=local,src=/tmp/.buildx-cache/linux/amd64
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture:
          - 'linux/amd64'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-buildx-${{ matrix.architecture }}-${{ github.sha }}
          path: /tmp/.buildx-cache/${{ matrix.architecture }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=local,src=/tmp/.buildx-cache/${{ matrix.architecture }}
          cache-to: type=local,dest=/tmp/.buildx-cache-new/${{ matrix.architecture }},mode=max
          context: .
          platforms: ${{ matrix.architecture }}
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache/${{ matrix.architecture }}
          mv /tmp/.buildx-cache-new/${{ matrix.architecture }} /tmp/.buildx-cache/${{ matrix.architecture }}
